# Generated by Django 2.2.4 on 2019-08-06 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_user_is_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_name',
            field=models.CharField(default='malamia', max_length=100),
            preserve_default=False,
        ),
    ]
