# Generated by Django 2.2.4 on 2019-09-09 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='create',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='phobe_number',
            new_name='phone_number',
        ),
    ]
